### ISSUE TITLE
Syntax error when running a patch action

### ISSUE THREAD

**Issue by gitMomo** [wesnick/api-platform-workflow-extension#3]
Hello @wesnick 

First i would like to thank you for this amazing extension :)

I have just a remark about the url in the potentialAction: 

Actually we have:

` "url": "/users/1?workflow=user_status&transition=ban_user"`

When i run this patch action, I get a syntax error from the API, but when i send the` { "transition": "ban_user" }` in the body it work... i don't know if it's an issue... or that's how it's supposed to work ?

If it's the second case, then is't possible to remove the transition part in the url ? 

thanks.

**Comment by wesnick** [comment]
Hi,

You can see in the tests some example payloads:
https://github.com/wesnick/api-platform-workflow-extension/blob/master/tests/EventListener/WorkflowOperationListenerTest.php#L56

Basically the URL needs workflow query param to make the workflow a resource.  So User object 1 will have workflows accessible via unique URL
/users/1?workflow=workflow_name
and the body payload indicates the mutation/transition you wish to perform on this resource.

The transition query parameter, if included, is currently ignored.

**Comment by gitMomo** [comment]
Thanks for your answer @wesnick, 

now i understand that the transition parameter is ignored in query, in this case can we remove it from the url included in the potentialAction ? 

`"url": "/users/1?workflow=user_status&transition=ban_user"`
to 
`"url": "/users/1?workflow=user_status"`

As we already have the transition name in the potentialAction details ? 

if you would like i can make a PR

Best Regards.
Momo

**Comment by wesnick** [comment]
> in this case can we remove it from the url included in the potentialAction

yes

> if you would like i can make a PR

great!
